### PR TITLE
updates

### PR DESCRIPTION
**Pull request by bvogel**

### CODE REVIEW

**Comment by bvogel** [comment]
@cice Can I haz an update -- pretty please?

**Comment by cice** [comment]
hey should i just merge this? what about rubygems, are you pushing it to rubygems?

**Comment by bvogel** [comment]
@cice You wrote end of January that I would get commit access to this repo, and I'd merge this myself but apparently I can't. I'd go ahead and try my luck on rubygems too, but as far as I can see, I still have no rights to push either.

**Comment by cice** [comment]
my bad. you are now collaborator on this repository, and co-owner on rubygems.

**Comment by bvogel** [comment]
Thank you, all set. BTW any news on your new implementation (you said late alpha in January...) 😉

**Comment by cice** [comment]
(y) We've been using the new implementation in production for > 6months now. I will definitely make it public, but i'm late on the documentation :). If you want to try it though, i can give you a quick example to start.

**Comment by bvogel** [comment]
sure, why not?

**Pull request merged**
